### ISSUE TITLE
linux/arm64 docker image is not found

### ISSUE THREAD

**Issue by wasif28** [blockscout/blockscout-rs#1001]
### Description

This is primarily an issue on Apple silicon based machines, where the docker image is not pulled and new nodes cannot use these with Kurtosis when spinning up new nodes.

### Type of the installation

Docker

### Type of the JSON RPC archive node

Geth

### Backend version

v6.7.2

### Elixir & Erlang/OTP versions

Elixir 1.16.3 , Erlang OTP 26.2.5.1

### Operating system

Mac M2

**Comment by bragov4ik** [comment]
I'll close this, as https://github.com/blockscout/blockscout-rs/issues/743 exists. (Probably will be completed in near future 👁️ 👁️)
