### ISSUE TITLE
stats: hidding a chart from blocksout/stats with ENV var

### ISSUE THREAD

**Issue by InoMurko** [blockscout/blockscout-rs#1045]
Is it possible to hide one of the charts with an environment variable? For example: `New transactions number` chart.

**Comment by InoMurko** [comment]
If I set 
```
STATS_CHARTS__LINE_CHARTS__AVERAGE_TXN_FEE__ENABLED: "false"
```
which when enabled returns:
```
2024-09-02T12:03:50.789844Z ERROR stats_server: service failed with error: unknown field `line_charts`, expected one of `counters`, `lines`, `template_values`
Error: unknown field `line_charts`, expected one of `counters`, `lines`, `template_values`
```

and from reading the code, this should be working??? charts.rs lines 279

```
      (
                "STATS_CHARTS__LINE_CHARTS__AVERAGE_TXN_FEE__ENABLED",
                "false",
            ),
        ]
        .map(|(s1, s2)| (s1.to_owned(), s2.to_owned()))
        .into();

        let expected_counter = ChartSettingsOverwrite {
            enabled: Some(true),
```

**Comment by InoMurko** [comment]
and then as per logs, I could change it to:
```
STATS_CHARTS__LINES__AVERAGE_TXN_FEE__ENABLED: false
```

```
2024-09-02T12:12:54.999829Z ERROR stats_server: service failed with error: unknown field `enabled`, expected one of `title`, `order`, `charts`
Error: unknown field `enabled`, expected one of `title`, `order`, `charts`
```

**Comment by bragov4ik** [comment]
Hi, I see what's the problem.

> and from reading the code, this should be working

The code in current `main` is an updated version (soon we'll release v2.0.0, it'll be the same). However, you seem to run the latest release ([v1.6.1](https://github.com/blockscout/blockscout-rs/tree/stats/v1.6.1)) that has a somewhat different structure of envs. So the code I linked should be relevant for the release.

Now, regarding the `STATS_CHARTS__LINES__AVERAGE_TXN_FEE__ENABLED`.
In that version the charts were placed inside categories (you can see it in [the config](https://github.com/blockscout/blockscout-rs/blob/d1f39cf77eb90d79e37ee92dc80293a27dba9014/stats/config/charts.json)). So to control settings for the chart you have to do:
`STATS_CHARTS__LINES__TRANSACTIONS__CHARTS__AVERAGE_TXN_FEE__ENABLED: false`

Hope it helps 😃

**Comment by InoMurko** [comment]
Ok, let me try.
Do you think it makes sense to document this better?

**Comment by bragov4ik** [comment]
> Do you think it makes sense to document this better?

documentation for envs is coincidentally in development exactly now 🙃 

> Does that mean you can't configure `New transactions` chart?

Why not? It's just going to be `NEW_TXNS` instead of `AVERAGE_TXN_FEE`

**Comment by InoMurko** [comment]
Oh I thought since they don't have `enabled` field that it wouldn't be possible. But I guess this property is optional.

Nevertheless, I'm running 1.6.1 and I've set:
```
STATS_CHARTS__LINES__TRANSACTIONS__CHARTS__AVERAGE_TXN_FEE__ENABLED: false 


2024-09-02T13:19:44.004188Z ERROR stats_server: service failed with error: unknown field `enabled`, expected one of `title`, `order`, `charts`
Error: unknown field `enabled`, expected one of `title`, `order`, `charts`
```

**Comment by InoMurko** [comment]
Does 1.6.1 keep the structure for schedules? 
```
  STATS_UPDATE_GROUPS__SCHEDULES__TOTAL_BLOCKS: "0 0 */1 * * * *" 
  STATS_UPDATE_GROUPS__SCHEDULES__ACTIVE_ACCOUNTS: "0 2 */1 * * * *"
  STATS_UPDATE_GROUPS__SCHEDULES__COMPLETED_TXNS: "0 5 */1 * * * *"
  STATS_UPDATE_GROUPS__SCHEDULES__TOTAL_ADDRESSES: "0 7 */1 * * * *"
  STATS_UPDATE_GROUPS__SCHEDULES__NEW_TXNS: "0 10 */1 * * * *"
  STATS_UPDATE_GROUPS__SCHEDULES__NEW_CONTRACTS: "0 15 */1 * * * *"
  STATS_UPDATE_GROUPS__SCHEDULES__NEW_VERIFIED_CONTRACTS: "0 30 */1 * * * *"
```

and `STATS_CHARTS__TEMPLATE_VALUES__NATIVE_COIN_SYMBOL`?

**Comment by InoMurko** [comment]
Alright, I think my config map was somehow stale and I got the wrong error logs. 
```
STATS_CHARTS__LINES__TRANSACTIONS__CHARTS__AVERAGE_TXN_FEE__ENABLED

STATS_CHARTS__LINES__TRANSACTIONS__CHARTS__NEW_TXNS__ENABLED
```
Is working for 1.6.1!

**Comment by bragov4ik** [comment]
you can check the changes [here](https://github.com/blockscout/blockscout-rs/blob/040868daae8e142440de231e3b5743451b19eba0/stats/config/migration/m20240618_080000_update_groups_and_separate_layout/README.md) for now
