### ISSUE TITLE
blockscout-db: The `addresses` table have no timestamp or block number for address when created.

### ISSUE THREAD

**Issue by yjhmelody** [blockscout/blockscout-rs#1063]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bragov4ik** [comment]
Can you provide more details? Repro steps or smth like that.

From the first look it seems like something for elixir repo

**Comment by bragov4ik** [comment]
Feel free to reopen when/if you have more details
