### ISSUE TITLE
stats: add arbitrum specific counters and charts

### ISSUE THREAD

**Issue by sevenzing** [blockscout/blockscout-rs#1079]
- [x] add new counter `totalOperationalTransactions`
- [x] charts `newOperationalTransactions`
- [x] `operationalTransactionsGrowth`
- [x] add env variable `ARBITRUM_ALL_ENABLED: bool`. if `true`, enable all charts and counter

basically this is `transactions - blocks` because in arbitrum every block emits additional so called "system" transaction and doesn't fully represent common user transaction.

counters and charts are disabled by default.

**Comment by bragov4ik** [comment]
the request is for all transactions, not just successful ones, right?
