### ISSUE TITLE
stats: The stats Docker container keeps restarting.

### ISSUE THREAD

**Issue by ddx2024** [blockscout/blockscout-rs#1126]
After starting with Docker Compose, the stats service keeps restarting, even though the logs appear normal.

<img width="1439" alt="image" src="https://github.com/user-attachments/assets/ecd5233e-eefe-41d1-8822-581862b69a31">

Below is the log content

<img width="1439" alt="image" src="https://github.com/user-attachments/assets/dd11a739-608a-4b1d-97cf-9a29a5d6ae00">

**Comment by bragov4ik** [comment]
Thanks for creating an issue. We've also noticed it; fix is out now 🎊 
https://github.com/blockscout/blockscout-rs/releases/tag/stats%2Fv2.2.3
