### ISSUE TITLE
visualizer : docker.io/library/proto:latest related Question

### ISSUE THREAD

**Issue by Ellen-Kang-03** [blockscout/blockscout-rs#1133]
I'm trying to build a docker image like this, but I get the following error. How can I solve this problem? Docker login is in the normal succeeded state. Should I change the repository address of docker.io/library/proto:latest or replace it with another package? Please help me. Thank you.

ubuntu@..:~/../blockscout-rs/visualizer$ sudo docker build -t ghcr.io/blockscout/visualizer:latest .
[+] Building 1.3s (4/4) FINISHED                                                  docker:default
 => [internal] load build definition from Dockerfile                                        0.0s
 => => transferring dockerfile: 750B                                                        0.0s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)              0.0s
 **=> ERROR [internal] load metadata for docker.io/library/proto:latest**                       1.3s
 => [internal] load metadata for ghcr.io/blockscout/services-base:latest                    0.5s
 => [internal] load metadata for docker.io/library/node:16-bullseye-slim                    1.1s
------
 > [internal] load metadata for docker.io/library/proto:latest:
------

 1 warning found (use docker --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
Dockerfile:12
--------------------
  10 |     RUN cargo chef cook --release --recipe-path recipe.json
  11 |     # Include proto common definitions (will be used in a `build-contexts` section)
  12 | >>> COPY --from=proto . /proto
  13 |     # Build application
  14 |     COPY . .
--------------------
ERROR: failed to solve: proto: failed to resolve source metadata for docker.io/library/proto:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

**Comment by GimluCom** [comment]
You can use the `--build-context proto=../proto` flag.
```sh
sudo docker build --build-context proto=../proto -t ghcr.io/blockscout/visualizer:latest .
```

**Comment by Ellen-Kang-03** [comment]
Thank you. It works well. Thank you :) !

**Comment by Ellen-Kang-03** [comment]
-
