### ISSUE TITLE
JSON payload (4638970 bytes) is larger than allowed (limit: 2097152 bytes).

### ISSUE THREAD

**Issue by youngqqcn** [blockscout/blockscout-rs#141]
When I verify contracts by standard input JSON  error output at web page: `JSON payload (4638970 bytes) is larger than allowed (limit: 2097152 bytes).`

**Comment by sevenzing** [comment]
hello, @youngqqcn , could you provide your standard JSON input (https://pastebin.com/ or smth)

**Comment by rimrakhimov** [comment]
Fixed in https://github.com/blockscout/blockscout-rs/pull/332. Now the maximum payload size may be specified via configuration variables. Adapted in [smart-contract-verifier-v1.0.0](https://github.com/blockscout/blockscout-rs/releases/tag/smart-contract-verifier%2Fv1.0.0) release
