### ISSUE TITLE
sig-provider: decode event arguments correctly

### ISSUE THREAD

**Issue by leviska** [blockscout/blockscout-rs#165]
Right now decoding event will not fail if some data was left, which can lead to wrong guesses
I suggest adding additional functions in ethabi: https://github.com/rust-ethereum/ethabi/pull/284, and then update our code using this function

**Comment by leviska** [comment]
We need also https://github.com/rust-ethereum/ethabi/pull/288 because there are additional cases, which are not found by offsets only

**Comment by sevenzing** [comment]
will be implemented during https://github.com/blockscout/blockscout-rs/issues/980
