### ISSUE TITLE
Generate an OpenAPI documentation

### ISSUE THREAD

**Issue by sevenzing** [blockscout/blockscout-rs#18]
There are two crates for generating open api docs: 
https://crates.io/crates/utoipa/1.1.0
https://crates.io/crates/utoipa-swagger-ui

For convinient integration with blockscout, we need to add swagger-ui page that will include all our endpoints

**Comment by rimrakhimov** [comment]
Closed as we couldn't find a way to do that through described frameworks. We decided to try to use protobuf files to describe HTTP endpoints and generate actix handlers from that. Current research is ongoing in #101
