### ISSUE TITLE
Blockscout Stats Service

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout-rs#184]
The Blockscout team identified a demand for the network charts feature in the explorer. Some partners have already handled the feature via 3rd parties: Celo embed a Google Data [view](https://explorer.celo.org/mainnet/stats), xDai added a Dune [dashboard](https://dune.com/maxaleks/xDai-Usage). Top other explorers’ implementations: [Etherscan](https://etherscan.io/charts), [Tronscan](https://tronscan.org/#/data/stats2/transaction), [Solscan](https://analytics.solscan.io/). So it seems reasonable to build the charts feature in Blockscout too.

Full description: https://www.notion.so/blockscout/Stats-8d49632f5fb1448a89ca4835c6c23b0c 

User Stories: 

- [x] 1. [Tech story] Create a basic service that fetches data from db and provides API
https://github.com/blockscout/blockscout-rs/issues/185
- [x] 2. Blocks stats
https://github.com/blockscout/blockscout-rs/issues/195
- [x] 3. Accounts stats
https://github.com/blockscout/blockscout-rs/issues/186
- [x] 4. Transactions stats
https://github.com/blockscout/blockscout-rs/issues/197
- [x] 5. Token stats
https://github.com/blockscout/blockscout-rs/issues/199
- [x] 6. Gas stats
https://github.com/blockscout/blockscout-rs/issues/198
- [ ] 7. Contracts stats
- [ ] 8. Network stats

**Comment by rimrakhimov** [comment]
The first iteration has been implemented
