### ISSUE TITLE
Docker: what folder to mount as volume for persistent data ?

### ISSUE THREAD

**Issue by lucgerrits** [blockscout/blockscout-rs#382]

**Comment by leviska** [comment]
Which service are you talking about?

**Comment by lucgerrits** [comment]
Sorry forgot to specify. Its for smart-contract-verifier using the ghcr.io/blockscout/smart-contract-verifier:0.6.0 docker image.

**Comment by leviska** [comment]
There are two config values 
https://github.com/blockscout/blockscout-rs/blob/main/smart-contract-verifier/smart-contract-verifier-server/config/base.toml#L13
https://github.com/blockscout/blockscout-rs/blob/main/smart-contract-verifier/smart-contract-verifier-server/config/base.toml#L32

Default values are the same as in this config (`/tmp/solidity-compilers`...)

These are not persistent data, but local cache for the compiler versions, i.e. it's only for performance, not for correctness, so you _can_ ignore them

If you want to reuse the cache between runs you can
1. Just mount some local folder as `/tmp/solidity-compilers` and the other
2. Specify the folder in the config/env variable, and mount into that folder

Let me know if you have any other questions

**Comment by lucgerrits** [comment]
Thanks @leviska  !
