### ISSUE TITLE
cannot load local compilers from `/tmp/solidity-compilers`

### ISSUE THREAD

**Issue by iulianivg** [blockscout/blockscout-rs#395]
After installing smart-contract-verifier-http and running `smart-contract-verifier-http` it turns into below warning/errror

```
2023-03-12T15:06:16.525160Z  WARN smart_contract_verifier::compiler::compilers: cannot load local compilers from `/tmp/solidity-compilers` dir: No such file or directory (os error 2)
2023-03-12T15:06:16.549512Z  INFO smart_contract_verifier::compiler::versions_fetcher: spawn version refresh job
2023-03-12T15:06:16.549586Z  WARN smart_contract_verifier::compiler::compilers: cannot load local compilers from `/tmp/vyper-compilers` dir: No such file or directory (os error 2)
```

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/43420841/224553659-9ee8783f-f2c4-4b61-8e4f-c22e785ccf9c.png">

I believe this warning escalates into further issues since on the frontend won't be able to select a solidity version for the compiler (not even the "default" one) 

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/43420841/224553853-97c1141e-478a-47bc-9f69-ea2a968f3497.png">

ENV variables

```
export DATABASE_URL=postgresql://whatever...@localhost:5432/my_explorer
export ETHEREUM_JSONRPC_VARIANT=geth
export NETWORK=POA
export SUBNETWORK=BITCOIN
export COIN_NAME=BTC
export ECTO_USE_SSL=false
export DISABLE_EXCHANGE_RATES=true
export BLOCK_TRANSFORMER=clique
**export ENABLE_RUST_VERIFICATION_SERVICE=true
export RUST_VERIFICATION_SERVICE_URL=http://0.0.0.0:8043/**
export CHAIN_ID=14333
export JSON_RPC=http://127.0.0.1:8545
export SECRET_KEY_BASE=13MY8E....
export ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:8545
export LOGO_FOOTER=/images/logo_footer.svg
export LOGO=/images/logo.svg
export SUPPORTED_CHAINS='[{title:"Test EVM",url:"https://test.website.com"}]'
```

**Comment by rimrakhimov** [comment]
@iulianivg Hi! Could you specify, what version of blockscout do you use?

**Comment by thempp66** [comment]
I have the same issue.
blockscout version: v5.1.1-beta

**Comment by blockinator** [comment]
@iulianivg run the following then start the verifier again:
```
mkdir /tmp/solidity-compilers
mkdir /tmp/vyper-compilers
```

That will only fix the warning but not the error with the not being able to select a solidity version for the compiler.

**Comment by def670** [comment]
I am running into this issue as well - was running ./smart-contract-verifier-http manually.  added in the compiler directorys (/tmp/solidity-compiler and vyper too).  @leviska how would you start smart-contract-verifier-server?  im not seeing an executable anywhere.

**Comment by blockinator** [comment]
BlockScout v5.0.0-beta works with the latest blockscout-rs version

**Comment by thempp66** [comment]
> BlockScout v5.0.0-beta works with the latest blockscout-rs version

It works with BlockScout v5.0.0-beta. Thanks!
