### ISSUE TITLE
Risky `starts_with()` Contract Source Code Verification Method 

### ISSUE THREAD

**Issue by Hellobloc** [blockscout/blockscout-rs#441]
## Introduction
The current contract source code verification is mainly done by compiling the contract and comparing it with the `Creation Tx Input`, but note that the comparison here is not verbatim. Instead, it determines whether the compiled result is the beginning of the on-chain contract. The details can be seen in the following code.
```rust
    fn compare_creation_tx_inputs(
        remote_bytecode: &Bytecode<T>,
        local_bytecode: &LocalBytecode<T>,
    ) -> Result<MatchType, VerificationErrorKind> {
        let remote_creation_tx_input = remote_bytecode.bytecode();
        let local_creation_tx_input = local_bytecode.bytecode();

        if remote_creation_tx_input.starts_with(local_creation_tx_input) {
            // If local compilation bytecode is prefix of remote one,
            // metadata parts are the same and we do not need to compare bytecode parts.
            return Ok(MatchType::Full);
        }

```
[link](https://github.com/blockscout/blockscout-rs/blob/main/smart-contract-verifier/smart-contract-verifier/src/verifier/all_metadata_extracting_verifier.rs#L200-L212)

## RISK
This approach makes an assumption that the compiler's compilation results are harder to control and that we cannot construct a source code so that its `bytecode` matches the beginning of other contract `bytecodes`, but there is a possible risk in this assumption!
### BASE CONTRACT
Here we give a `base contract`, which has an `inline assembly return` in the `constructor`. The final bytecode often contains only a very simple and controlled part of the `creation code`, there is no `Runtime Code` and `Metadata`, and such a contract provides the `basis` for our later attack ideas.
```solidity
pragma solidity = 0.4.26;
contract base{
    uint a;
    constructor() public payable{
        assembly{
            return(0x0,0x0)
        }
    }
    function b() public payable{
        a = 400;
    }
}
//Compile Output : 60806040520000
```
### Let's Do it
This gives us the possibility to perform a false verification and lets us go one step further. We are now going to try to construct two contracts `A` , `A_1` by `inline assembly`. and make the compiled result of `A_1` the beginning of the compiled result of `A`.

Here we give the final construction result directly:
```solidity
//open the Optimizer in 200
//The optimizer is turned on, but note that not turning on the optimizer does not affect my ability to construct examples like this
pragma solidity = 0.4.26;
contract A{
    uint a;
    constructor() public payable{
    }
    function b() public payable{
        a = 100;
    }

}
//Compile Output : 6080604052607e8060116000396000f300608060405260043610603e5763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416634df7e3d081146043575b600080fd5b6049604b565b005b60646000555600a165627a7a72305820d4b6ced9c1e200a550fefae535dae0978bda13fbffa7a3621f1a73285644c86f0029
```
```solidity
//open the Optimizer in 200 
//The optimizer is turned on, but note that not turning on the optimizer does not affect my ability to construct examples like this
pragma solidity = 0.4.26;
contract A_1{
    uint a;
    constructor() public payable{
        assembly{
            0x7e
            dup1
            0x11
            0x00
            codecopy
            0x00
            return
        }
    }
    function b() public payable{
        a = 400;
    }
}
//Compile Output : 6080604052607e8060116000396000f300
```
The `bytecodes` of the above two contracts cannot be found here:

`6080604052607e8060116000396000f300`
`6080604052607e8060116000396000f30060806040....1a73285644c86f0029`

```rust
#![allow(unused)]
fn main() {
let a_code = "6080604052607e8060116000396000f300608060405260043610603e5763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416634df7e3d081146043575b600080fd5b6049604b565b005b60646000555600a165627a7a7230582073d653de144a2676ecba42ef4a138d08c58ce6187d82a1daa240d5f9339787100029";
let a_1_code = "6080604052607e8060116000396000f300";

assert!(a_code.starts_with(a_1_code));
}
```
This means that the bytecode of `A_1` is the beginning of `A`.

**_The good news is that not all contracts can be constructed this easily, for example some contracts will have fields like `PUSH1 0x0012` in the `constructor` section, such fields are harder to construct in inline assembly because `0x0012` generates `PUSH 0x12`._**

**_Secondly, in `0.4+` contracts, given the need to build inline assemblies based on the `yul` syntax, constructing the exact same `bytecode` also becomes difficult, but this just means that there are difficulties in the construction of the attack, it is not considered infeasible and may require a deeper study of the `compiler`._**
## Impact
Such an attack could result in some contract source code being preempted by a malicious user with a meaningless source code.
It will of course also allow us to arbitrarily construct the non-constructor part of the source code and even make the result contain a correct `ABI`.

## Recommend 
We recommend adding more checks on the `compile_output` to eliminate such compilation results without `runtime` code, e.g. to determine the presence of `compile.depolyedcode` in the `compile_output`.
**_In essence, one of my previous ideas was to generate a contract with `no compile output` via an `abstract contract`, and then bypass your `strats_with` validation. But after trying it, I found that I couldn't get through, but it was beautifully done, and I was wondering if you had done a special design for it._**

**Comment by Hellobloc** [comment]
@rimrakhimov

**Comment by Hellobloc** [comment]
https://github.com/ethereum/sourcify/releases/tag/v2.1.1
I have also recently discovered two vulnerabilities in Sourcify and I see that you have done a lot of work on Sourcify's source code validation as well, so share it to see if we can have more discussions. <3

**Comment by Hellobloc** [comment]
etherscan is not open source, leaving us with no way of knowing how it works.
![image](https://user-images.githubusercontent.com/113746997/233652844-9d548044-bd71-4b34-b385-95f2345510bd.png)

**Comment by rimrakhimov** [comment]
Hi, @Hellobloc. Thank you for your research once again!

I'm not sure if such a check may actually cause an invalid source code to be verified. We use the `starts_with` to check what we assume to be a compiled part of the creation input, but it is not the final verification step. All remaining bytes we consider as constructor arguments that have to be correctly decoded accorded to contract abi ([Link](https://github.com/blockscout/blockscout-rs/blob/main/smart-contract-verifier/smart-contract-verifier/src/verifier/all_metadata_extracting_verifier.rs#L186)). Thus, it seems that the contract you provided would not be verified (at least, I couldn't, maybe just did something wrong?).

The question I still have is whether it would be possible to use your approach if the original contract has some constructor arguments (e.g., `bytes`). I couldn't come up with that quickly but seems that it still may be possible

**Comment by Hellobloc** [comment]
Hi, @rimrakhimov  Yes, thank you very much for the reminder.

Actually, I also encountered the problem of abi checking when I was actually verifying, and it was indeed a problematic point that we needed to construct a case of a constructor with more than one input parameter.

But this is really much harder, I tried to construct it and it didn't work out. I think this might be a false report.
