### ISSUE TITLE
error: failed to run custom build command 

### ISSUE THREAD

**Issue by alishaMaharani** [blockscout/blockscout-rs#456]
error: failed to run custom build command for `smart-contract-verifier-proto v0.1.0 (/root/.cargo/git/checkouts/blockscout-rs-1329d74b8bb8dea8/9b01e2b/smart-contract-verifier/smart-contract-verifier-proto)`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installIqlcbK/release/build/smart-contract-verifier-proto-757fb223386219c9/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=proto/

  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: protoc-gen-openapiv2: program not found or is not executable\nPlease specify a program using absolute path or make sure the program is available in your PATH system variable\n--openapiv2_out: protoc-gen-openapiv2: Plugin failed with status code 1.\n" }
warning: build failed, waiting for other jobs to finish...
error: failed to compile `smart-contract-verifier-server v0.1.0 (https://github.com/blockscout/blockscout-rs#9b01e2bc)`, intermediate artifacts can be found at `/tmp/cargo-installIqlcbK`

protoc --version
libprotoc 22.4

**Comment by rimrakhimov** [comment]
During proto file compilation we also generate OpenApi definition for what [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway#installation) is required. You may find one of the ways to install it in our CI pipeline (https://github.com/blockscout/blockscout-rs/blob/main/.github/actions/deps/action.yml#L21)
