### ISSUE TITLE
Cannot verify contract that has immutable variables and is deployed from genesis

### ISSUE THREAD

**Issue by hlhdaiaaii** [blockscout/blockscout-rs#471]
I have a set of contracts containing immutable variables at genesis. I try to verify them with _constructorArguments_  but it threw "Fail - Unable to verify" through API method and "No contract could be verified with provided data" through explorer interface. I know the on-chain runtime bytecode of these contracts would be different from the runtime bytecode generated from the compiler since placeholders for immutable variables must be fulfilled through constructor. Does the current version of blockscout already handle this case?

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System: Ubuntu
* Blockscout Version/branch/commit: [314b84390a3ecd81bfb16de012517435a0684c37](https://github.com/blockscout/blockscout/commit/314b84390a3ecd81bfb16de012517435a0684c37)
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

### Steps to reproduce

Run a blockchain from a genesis file defining runtime bytecode of contract whose constructor is already called.

### Expected behaviour

Should verify successfully

### Actual behaviour

Cannot verify

**Comment by rimrakhimov** [comment]
Hi, @hlhdaiaaii! No, currently blockscout supports the verification of contracts with immutable variables which only have creation inputs. The contracts that have deployed bytecodes only couldn't be verified in that case

**Comment by hlhdaiaaii** [comment]
Thanks for your clarification. Then I resort to customizing my blockchain to deploy these contracts at block 1 as system transaction instead.

**Comment by Thegaram** [comment]
Hi @rimrakhimov, we have the same setup on our chain: A contract with `immutable` variables predeployed in genesis. Do you plan to support verification for such contracts in the future?
