### ISSUE TITLE
Same Name Contract Issue

### ISSUE THREAD

**Issue by Hellobloc** [blockscout/blockscout-rs#530]
## Introduction
The current source code results for the compilation target are located by contract name, and the path information is missing. This means that we can construct two contracts with the same name in one source code. In the end,  we cannot locate the only contract as our compilation target.

## Impact
Attackers can use the eponymous contract issue to confuse users and hide backdoors in the code.
## Attack Case
https://optimism-goerli.blockscout.com/address/0x3C10387CF5cC4B655d12898C3628AF38C5E792c2?tab=contract
https://goerli-optimism.etherscan.io/address/0x3C10387CF5cC4B655d12898C3628AF38C5E792c2#code
![image](https://github.com/blockscout/blockscout-rs/assets/113746997/db04a5cb-32ac-4ee5-b00f-fc128bba5d68)
![image](https://github.com/blockscout/blockscout-rs/assets/113746997/496a2e7b-b412-40cf-95d5-f4d329bebfcd)
![image](https://github.com/blockscout/blockscout-rs/assets/113746997/73a61cca-3713-4ef3-99de-1c6d2b67c6f6)

**Comment by Hellobloc** [comment]
@rimrakhimov

**Comment by rimrakhimov** [comment]
Hi, @Hellobloc! It seems that the main contract file is indicated as the only file opened in the editor by default. When the contract tab is opened there is only the "test.sol" file shown to the user. 

I agree that it may be not quite obvious though. We will discuss it with our frontend team how we can make it more informative. Just would like to make sure that I got you right and the main concern here is not some algorithmic issue but more the data description inside the UI

**Comment by Hellobloc** [comment]
@rimrakhimov Thank you very much for your quick response and the attention you have given to these issues.
Yes, it is a UI presentation issue and it is a ambiguity risk due to contract name not containing path information.

**Comment by rimrakhimov** [comment]
@Hellobloc I see. We'll discuss it with our design team how we can indicate that more clearly to the users. Thank you

**Comment by tom2drum** [comment]
@Hellobloc we've prepared a little [demo](https://review-tom2drum-issue-975.k8s-dev.blockscout.com/address/0x4fdaCE0cDb4eb9fd102df757808Ae6d83cF8af15?tab=contract) how we are going to mitigate this issue in the UI. We've added `file path` field into the contract general info section and also an indicator of the main file to the tabs and files tree. Please take a look and tell us what you think.

<img width="1419" alt="Screenshot 2023-07-06 at 9 27 54 AM" src="https://github.com/blockscout/blockscout-rs/assets/22130104/17124d94-fe7b-496f-91db-38b3a9607b29">
