### ISSUE TITLE
Reinit Issue

### ISSUE THREAD

**Issue by Hellobloc** [blockscout/blockscout-rs#531]
## Introduction
Just as we are familiar with the reinit problem is the deployment of two different runtime codes on the same address via create2.
This can lead to a mismatch in our source code, and we found that Blockscout's source code results do not warn about reinit, which causes the source code mismatch to go unnoticed by the public.

Blockscout will provide a reinit warning, but it doesn't report any errors when inheriting sourcify's source code.
## Impact
An attacker can use this feature to hide a backdoor in the source code and defraud the public.
## Attack Case
https://goerli.optimism.blockscout.com/address/0x341577fB771EBFB4FaF74fBcF786d4F7Ce02BBaB
![image](https://github.com/blockscout/blockscout-rs/assets/113746997/327680fe-e6c8-4cdf-857b-5a7513f2a803)
![image](https://github.com/blockscout/blockscout-rs/assets/113746997/dfb83717-46cc-4746-898a-cb08566e6320)

If you fix this, please be sure to leave the attack case above, thank you very much!

**Comment by rimrakhimov** [comment]
Hmm, that is really a problem.

It seems to be related to the fact that we don't know the bytecode of the contract used for the verification when pulling the sources from Sourcify. I still have no clear vision of how to fix it, though.. 

As far as I know there is no way to obtain the bytecode of the contract used by the Sourcify, isn't it? I believe, it should be the same problem with Sourcify repository. Haven't you discussed that with their team?

Anyway, thank you for the report!

**Comment by Hellobloc** [comment]
Hello, @rimrakhimov . Thank you very much for your reply and further communication.
This is the [issue ](https://github.com/ethereum/sourcify/issues/1067)in Sourcify that discusses the reinit issue, and I thought it could be discussed publicly here so that other explorers could benefit from it as well.
