### ISSUE TITLE
Can't display SuperSubmission ChainID

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout-rs#559]
https://admin-ts-test.k8s-dev.blockscout.com/admin/resources/SuperSubmissions/records/1/show

1. Open SuperSubmissions tab
2. Then open Users tab
3. Repeat step 1

Expected result: ChainID is displayed
Actual result:
![Image](https://user-images.githubusercontent.com/108135703/253047069-a64bfe21-639b-47a1-a1eb-7783cc212299.png)

**Comment by rimrakhimov** [comment]
It looks like it is not consistent behaviour. Sometimes the chain name is represented correctly, but sometimes the error is displayed
