### ISSUE TITLE
Research on jumps to public function in solidity code

### ISSUE THREAD

**Issue by sevenzing** [blockscout/blockscout-rs#571]
Source issue: https://github.com/blockscout/frontend/issues/1016

Research how to extract mapping `functionName -> fileLocation` from verified contract

**Comment by rimrakhimov** [comment]
https://github.com/sevenzing/sol-abi-jumps

**Comment by rimrakhimov** [comment]
The concept itself seems to be working. For now there are several issues needed to be fixed before the service could be implemented. The main is that we need an `evm.bytecode.sourceMap` input for all verified contracts. Currently, we neither keep that info, nor compile it at all.

1. Update verification service to output `sourceMap` during the compilation, and return it as a VerificationResult
2. Update eth-bytecode-db service to return `sourceMap` as a VerificationResult and to store that info inside the internal database
1. Update blockscout database schema to store the output of the `sourceMap`
2. Recompile all verified contracts and store `sourceMap` for them
