### ISSUE TITLE
Add additional field "description" to counter's endpoint

### ISSUE THREAD

**Issue by sevenzing** [blockscout/blockscout-rs#610]
Tooltip texts for all number charts:

1) Average block time
Description: Average time taken in seconds for a block to be included in the blockchain

2) Total accounts
Description: Number of EOAs that sent at least 1 transaction

3) Total tokens
Description: Number of all token contracts

4) Completed txns
Description: Number of transactions with success status

5) Total blocks
Description: Number of blocks over all time

6) Total txns
Description: All transactions including pending, dropped, replaced, failed transactions

7) Number of deployed contracts today
Description: Number of deployed contracts today

8) Total contracts
Description: Number of contracts

9) Total verified contracts
Description: Number of verified contracts

10) Number of verified contracts today
Description: Number of contracts verified today

11) Total native coin transfers
Description: Number of transactions with the transfer of the native coin

12) Total addresses
Description: Number of addresses that participated in the blockchain

**Comment by sevenzing** [comment]
Testing stand avaliable on 

https://blockscout-main.k8s-dev.blockscout.com/stats
https://stats-test.k8s-dev.blockscout.com/api/v1/counters

**Comment by yvaskov** [comment]
Frontend task https://github.com/blockscout/frontend/issues/1151 is ready for release and approved
