### ISSUE TITLE
Smart contract verification doesn't work on Goerli/Sepolia

### ISSUE THREAD

**Issue by yvaskov** [blockscout/blockscout-rs#619]
## Description

I've tried verifying with Solidity flattened SC, got infinite loading, no positive/negative result.

**Comment by rimrakhimov** [comment]
The problem has not been seen in the last few months. We've improved logging inside the verification and eth-bytecode-db services, so the next time the problem occurs we may observe the problem.

But for now, I believe the issue can be closed. @yvaskov wdyt?

**Comment by yvaskov** [comment]
Agree, closing
