### ISSUE TITLE
Blockscout can not verify contracts which require via-ir

### ISSUE THREAD

**Issue by JABirchall** [blockscout/blockscout-rs#631]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker
* Elixir & Erlang/OTP versions (`elixir -version`): N/A
* Node JS version (`node -v`):N/A
* Operating System: Debian
* Blockscout Version/branch/commit: 5.2.1
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

### Steps to reproduce

Uniswap Permit2 requires via-ir to compile due to the amount of slots it uses. 
However, upon verifying the contract, blockscout can not as it does not use via-ir to verify. 

Use https://github.com/Uniswap/permit2 or sync with ethereum and use address https://eth.blockscout.com/address/0x000000000022D473030F116dDEE9F6B43aC78BA3?tab=txs

PS: also looks like a second issue where the official blockscout explorer does not recognise that address as a contract.

Compared with https://etherscan.io/address/0x000000000022D473030F116dDEE9F6B43aC78BA3

### Expected behaviour

Add an option to blockscout verify contract page to enable via-ir switch

### Actual behaviour

Blockscout fails to verify the contract with the this error:
```
Compilation error: ["CompilerError: Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.\n --> Permit2.sol:947:45:\n |\n947 | permit, transferDetails, owner, permit.hashWithWitness(witness, witnessTypeString), signature\n | ^^^^^^\n\n"]
```

**Comment by rimrakhimov** [comment]
@JABirchall Could you please share what method do you use for contract verification? And the input itself would be really great

**Comment by JABirchall** [comment]
> @JABirchall Could you please share what method do you use for contract verification? And the input itself would be really great

Im trying to verify the contract on my own chain here: https://explorer.rethereum.org/address/0x000000000022D473030F116dDEE9F6B43aC78BA3/verify-via-flattened-code/new

Fork the permit2 repo: https://github.com/Uniswap/permit2

Run `forge flatten src/Permit2.sol`

Copy the flatten code into code box. 

Set optimizer to 1000000.

Observe stack too deep compile error:

![](https://i.imgur.com/gksNkM3.png)

**Comment by rimrakhimov** [comment]
You cannot set `via-ir` option via Flattened verification method. Try to use Standard-json and set the optimization there (you may find the following [link](https://docs.blockscout.com/for-users/verifying-a-smart-contract/openzeppelin-contract-verification#manual-standard-input-json-with-remix) useful)

**Comment by JABirchall** [comment]
> You cannot set `via-ir` option via Flattened verification method. Try to use Standard-json and set the optimization there (you may find the following [link](https://docs.blockscout.com/for-users/verifying-a-smart-contract/openzeppelin-contract-verification#manual-standard-input-json-with-remix) useful)

Thanks, building and uploading a standard-input.json worked.
