### ISSUE TITLE
Stats: `charts.toml` not working but `charts.json` does

### ISSUE THREAD

**Issue by mayone** [blockscout/blockscout-rs#693]
# Version
- Image version: `v1.5.0`

# Brief
- When using `STATS__CHARTS_CONFIG` to run [stats](https://github.com/blockscout/blockscout-rs/tree/main/stats)
- [`charts.toml`](https://github.com/blockscout/blockscout-rs/blob/main/stats/config/charts.toml) not working.
  - which is updated 5 months ago.
- [`charts.json`](https://github.com/blockscout/blockscout-rs/blob/main/stats/config/charts.json) will work.
  - which is updated 3 months ago.

# Description
It seems that either the file [`charts.toml`](https://github.com/blockscout/blockscout-rs/blob/main/stats/config/charts.toml) is **outdated**, or it's not supported anymore.
I failed to run with this file but run successfully with the [`charts.json`](https://github.com/blockscout/blockscout-rs/blob/main/stats/config/charts.json).
Maybe the README should be updated too.

**Comment by frisitano** [comment]
Also experiencing this problem

**Comment by bragov4ik** [comment]
We are removing support for `.toml` config in the next release, so this issue is now resolved 🙃 🙃
