### ISSUE TITLE
How to clean up ghcr.io/blockscout/stats:latest as it takes up too much disk space?

### ISSUE THREAD

**Issue by phpmac** [blockscout/blockscout-rs#900]
如何清理 ghcr.io/blockscout/stats:latest 占用磁盘太大了

**Comment by bragov4ik** [comment]
Hello!
Can you provide more details on your issue?
- how do you run it?
- how much disk space does it use?
- why is it too much?

**Comment by bragov4ik** [comment]
Feel free to reopen it when/if you have more info 👀

**Comment by phpmac** [comment]
实际上是输出的日志太多，应该在哪里关闭？

**Comment by bragov4ik** [comment]
I use google translate: "There are actually too many logs being output. Where should I turn them off?"

Answering this question, you can soften the log level with `RUST_LOG=warn`, or disable logs entirely in the service by `STATS__TRACING__ENABLED=false`.

Another option can be to somehow remove the old logs but it depends on the setup; I think the internet will be helpful with ways to clear docker output ("docker log rotation" maybe? 🤔 ).

**Comment by phpmac** [comment]
"There are actually too many logs being output. Where should I turn them off?"
>
Answering this question, you can soften the log level with `RUST_LOG=warn`, or disable logs entirely in the service by `STATS__TRACING__ENABLED=false`.
>
Another option can be to somehow remove the old logs but it depends on the setup; I think the internet will be helpful with ways to clear docker output ("docker log rotation" maybe? 🤔 ).

Only by turning off the log output can I attempt to clean up. The cleanup is effective. My current solution is to set up a scheduled task, but according to the production environment, it is unnecessary to output some insufficient logs, as they will occupy my disk space.

thankyou bro

**Comment by bragov4ik** [comment]
I can't really understand what you mean, sorry 🙈 . Anyway, it seems that the issue has been resolved, so you're welcome :)
