### ISSUE TITLE
Native coin

### ISSUE THREAD

**Issue by InoMurko** [blockscout/blockscout-rs#921]
Currently, the NATIVE COIN is read from a file, which means it's really a pickle to modify on the fly. The ability to set it via `STATS__NATIVE_COIN` env var would be much more easily adjustable.

**Comment by bragov4ik** [comment]
It is possible to set config values via envs starting with `STATS_CHARTS__*`. For `native_coin_symbol` template, the variable should be `STATS_CHARTS__TEMPLATE_VALUES__NATIVE_COIN_SYMBOL`.

**Comment by bragov4ik** [comment]
By the way, the variable might change soon, but the idea remain the same

**Comment by InoMurko** [comment]
Oooof, certainly! Thanks! 🙏🏻

**Comment by InoMurko** [comment]
Awesome! Please document and it won't be an issue.
