### ISSUE TITLE
make api for swagger

### ISSUE THREAD

**Issue by sevenzing** [blockscout/blockscout-rs#990]
need to add endpoint like `/api/swagger` that will return raw OpenAPI swagger file

related to https://github.com/blockscout/frontend/issues/2070

**Comment by bragov4ik** [comment]
Works on staging: `curl https://stats-sepolia.k8s-dev.blockscout.com/api/v1/docs/swagger.yaml`

**Comment by bragov4ik** [comment]
https://github.com/blockscout/blockscout-rs/pull/1007
and
https://github.com/blockscout/blockscout-rs/pull/1027
