### ISSUE TITLE
My contract not veryfai 

### ISSUE THREAD

**Issue by anasrangrej159** [blockscout/blockscout-rs#996]
### Description

My contract is not getting verified please help me I have tried to do so but still the contract is not getting verified please help me

### Type of the installation

Helm charts (k8s)

### Type of the JSON RPC archive node

Gnosis erc-20

### Type of the chain

L1

### Link to the page

https://gnosis.blockscout.com/address/0x16da39ACB6043D8152Ee1A898af978b199EC2936

### Steps to reproduce

My contract not being veryfai 

### Backend version

v6.7.2-beta

### Frontend version

v1.32.1+0c82ce15

### Elixir & Erlang/OTP versions

1.16.3

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 11; RMX3151) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 Mobile Safari/537.36

**Comment by anasrangrej159** [comment]
Please help me

**Comment by sevenzing** [comment]
if this issue is still relevant please provide source of your contract, method of verification and settings you provide to blockscout, otherwise we will close the issue

**Comment by bragov4ik** [comment]
feel free to reopen when/if you have more details

**Comment by anasrangrej159** [comment]
My usdc translation is not working

**Comment by anasrangrej159** [comment]
My token is not getting translated, it is showing an error
